// The tooltip catalog: the single source of truth for what every control in the app does,
// its Genos name, its keyboard shortcut and where it lives on the Launchkey.
//
// - Every interactive element in the UI carries `data-tip="<key>"` (via `use:tip`), and a
//   test fails if one doesn't or if the key isn't in this catalog.
// - `keys` are written the way README's "Terminal keys" list writes them (`space`,
//   `shift+1`, `F10`, `←`), and a test checks them against README both ways.
// - Pad locations use `padLocation()`'s wording, and a test checks each pad's entry names
//   the pad it's on.
// - `npm run docs:controls` renders this catalog to `app/docs/controls.md`.

export interface Tip {
  /** The control's name, as the app labels it. */
  title: string
  /** What it does, in one to three plain sentences. */
  body: string
  /** The Genos name, when it has one (null: yahaha-only, or the same as the title). */
  genos: string | null
  /** Keyboard shortcuts, README notation. Empty: no shortcut. */
  keys: string[]
  /** Where it is on the Launchkey. null: not on the Launchkey. */
  launchkey: string | null
  /**
   * Keys the app uses instead of `keys`, where the terminal's key would break the app's
   * keyboard navigation (Tab moves focus in the app, so pad pages are PgUp/PgDn here).
   */
  app_keys?: string[]
}

const P1 = 'Pad page 1 (Sections)'
const P2 = 'Pad page 2 (Chord/Setup)'
const P3 = 'Pad page 3 (OTS/Parts)'
const P4 = 'Pad page 4 (Registration)'
const pad = (page: string, row: 'top' | 'bottom', n: number) => `${page}, ${row} row, pad ${n}`

const catalog = {
  // ── Transport ───────────────────────────────────────────────────────────
  'transport.start_stop': {
    title: 'Start / Stop',
    body: 'Starts the band right away, or stops it. Starting from a stop plays the armed Intro first, if you picked one.',
    genos: 'START/STOP',
    keys: ['space'],
    launchkey: `${pad(P1, 'bottom', 8)}; Play button`,
  },
  'transport.stop': {
    title: 'Stop',
    body: 'Stops the band. Unlike Start / Stop it never starts it.',
    genos: 'START/STOP (stop)',
    keys: [],
    launchkey: 'Stop button',
  },
  'transport.sync_start': {
    title: 'Sync Start',
    body: 'Arms the band to start on your first left-hand chord. The lamp pulses while it waits. Pressing it while the band plays stops the band and re-arms.',
    genos: 'SYNC START',
    keys: ['y'],
    launchkey: pad(P1, 'top', 4),
  },
  'transport.sync_stop': {
    title: 'Sync Stop',
    body: 'The band plays only while you hold a chord: let go of every chord key and it stops, play again and it restarts. Not available with the Full Keyboard fingerings.',
    genos: 'SYNC STOP',
    keys: ['j'],
    launchkey: pad(P1, 'bottom', 7),
  },
  'transport.auto_fill': {
    title: 'Auto Fill',
    body: 'When on, switching to another Main plays a fill into it first.',
    genos: 'AUTO FILL IN',
    keys: ['u'],
    launchkey: pad(P1, 'top', 8),
  },
  'transport.stop_acmp': {
    title: 'Stop ACMP',
    body: 'With Sync Start off and the band stopped, a chord you hold sounds on the style\'s bass and pad voices.',
    genos: 'Stop Accompaniment',
    keys: ['h'],
    launchkey: pad(P2, 'bottom', 2),
  },
  'transport.fade': {
    title: 'Fade In/Out',
    body: 'Stopped, it arms a fade in: the next start comes up from silence. Playing, the band fades out and stops, and stays silent for the hold time before its volume comes back (only the style fades, not what you play). The fade times are in Settings › Style.',
    genos: 'Fade In/Out (Assignable)',
    keys: ['F'],
    launchkey: `${pad(P3, 'top', 6)}; Shift + Stop button`,
  },
  'transport.section_reset': {
    title: 'Section Reset',
    body: 'Starts the section playing again from its top, right now, for stutter effects. With Section Reset on in Settings › Style (the default), Tap does the same while the band plays.',
    genos: 'Style Section Reset (TAP TEMPO)',
    keys: ['|'],
    launchkey: 'Shift + Play button',
  },
  'transport.retrigger': {
    title: 'Retrigger',
    body: 'While on, each chord you play restarts the Main and loops its first few beats (the Retrigger length) until you change section or turn it off. Only Mains retrigger.',
    genos: 'Style Retrigger (RtgOnOff)',
    keys: ['~'],
    launchkey: pad(P2, 'bottom', 8),
  },
  'transport.retrigger_shorter': {
    title: 'Retrigger length shorter',
    body: 'Makes the Retrigger loop one step shorter: 1, 1/2, 1/4, 1/8, 1/16, 1/32 of a whole note.',
    genos: 'Style Retrigger Rate (RtgRate)',
    keys: ['}'],
    launchkey: 'Shift + > (Scene Launch) button',
  },
  'transport.retrigger_longer': {
    title: 'Retrigger length longer',
    body: 'Makes the Retrigger loop one step longer, up to a whole note.',
    genos: 'Style Retrigger Rate (RtgRate)',
    keys: ['{'],
    launchkey: 'Shift + Function button',
  },
  'transport.panic': {
    title: 'Panic',
    body: 'Sends all notes off on every part, for a stuck note.',
    genos: null,
    keys: ['\\'],
    launchkey: null,
  },

  // ── Sections ────────────────────────────────────────────────────────────
  'section.intro1': {
    title: 'Intro I',
    body: 'Stopped: arms Intro I to play when the band starts (the lamp pulses). Playing: queues it for the next bar.',
    genos: 'INTRO I',
    keys: ['q'],
    launchkey: pad(P1, 'top', 1),
  },
  'section.intro2': {
    title: 'Intro II',
    body: 'Stopped: arms Intro II to play when the band starts (the lamp pulses). Playing: queues it for the next bar.',
    genos: 'INTRO II',
    keys: ['w'],
    launchkey: pad(P1, 'top', 2),
  },
  'section.intro3': {
    title: 'Intro III',
    body: 'Stopped: arms Intro III to play when the band starts (the lamp pulses). Playing: queues it for the next bar. Dark if the style has none.',
    genos: 'INTRO III',
    keys: ['e'],
    launchkey: pad(P1, 'top', 3),
  },
  'section.main_a': {
    title: 'Main A',
    body: 'Switches to Main A at the next bar; the lamp flashes while queued. Press the Main that is playing to play its fill, which also flashes.',
    genos: 'MAIN VARIATION A',
    keys: ['1'],
    launchkey: pad(P1, 'bottom', 1),
  },
  'section.main_b': {
    title: 'Main B',
    body: 'Switches to Main B at the next bar; the lamp flashes while queued. Press the Main that is playing to play its fill, which also flashes.',
    genos: 'MAIN VARIATION B',
    keys: ['2'],
    launchkey: pad(P1, 'bottom', 2),
  },
  'section.main_c': {
    title: 'Main C',
    body: 'Switches to Main C at the next bar; the lamp flashes while queued. Press the Main that is playing to play its fill, which also flashes.',
    genos: 'MAIN VARIATION C',
    keys: ['3'],
    launchkey: pad(P1, 'bottom', 3),
  },
  'section.main_d': {
    title: 'Main D',
    body: 'Switches to Main D at the next bar; the lamp flashes while queued. Press the Main that is playing to play its fill, which also flashes.',
    genos: 'MAIN VARIATION D',
    keys: ['4'],
    launchkey: pad(P1, 'bottom', 4),
  },
  'section.break': {
    title: 'Break',
    body: 'Plays the break from the next beat to the end of the bar, then goes back to the Main. The lamp flashes while it waits for the beat.',
    genos: 'BREAK',
    keys: ['g'],
    launchkey: pad(P1, 'bottom', 5),
  },
  'section.ending1': {
    title: 'Ending I',
    body: 'Plays Ending I from the next bar, then stops the band. Press it again while it plays to slow down to the end (ritardando).',
    genos: 'ENDING/rit. I',
    keys: ['i'],
    launchkey: pad(P1, 'top', 5),
  },
  'section.ending2': {
    title: 'Ending II',
    body: 'Plays Ending II from the next bar, then stops the band. Press it again while it plays to slow down to the end (ritardando).',
    genos: 'ENDING/rit. II',
    keys: ['o'],
    launchkey: pad(P1, 'top', 6),
  },
  'section.ending3': {
    title: 'Ending III',
    body: 'Plays Ending III from the next bar, then stops the band. Press it again while it plays to slow down (ritardando); dark if the style has none.',
    genos: 'ENDING/rit. III',
    keys: ['p'],
    launchkey: pad(P1, 'top', 7),
  },
  'section.lamps': {
    title: 'Section lamps',
    body: 'Dim: available. Bright: playing, or on. Flashing: queued for the next bar (fills: the next beat). Pulsing: armed and waiting for you. Dark: this style doesn\'t have it.',
    genos: 'Section lamp states',
    keys: [],
    launchkey: 'The pads light the same way, in the same colours',
  },

  // ── Tempo and display ───────────────────────────────────────────────────
  'tempo.tap': {
    title: 'Tap tempo',
    body: 'Tap two or more times in time to set the tempo from your taps. While the band plays, a tap restarts the section instead (Section Reset), unless you turn that off in Settings › Style. The pad lights on the downbeat while the band plays.',
    genos: 'TAP TEMPO',
    keys: ['t'],
    launchkey: pad(P1, 'bottom', 6),
  },
  'tempo.down': {
    title: 'Tempo −',
    body: 'Slows the tempo by 1 BPM.',
    genos: 'TEMPO −',
    keys: ['-'],
    launchkey: 'Function button (right of the pads)',
  },
  'tempo.up': {
    title: 'Tempo +',
    body: 'Speeds the tempo up by 1 BPM.',
    genos: 'TEMPO +',
    keys: ['='],
    launchkey: '> (Scene Launch) button (right of the pads)',
  },
  'display.tempo': {
    title: 'Tempo',
    body: 'The current tempo in beats per minute. Loading a style sets the style\'s own tempo.',
    genos: 'Tempo',
    keys: [],
    launchkey: null,
  },
  'display.timesig': {
    title: 'Time signature',
    body: 'The style\'s time signature, from the style file.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'display.position': {
    title: 'Bar and beat',
    body: 'Where the band is: bar, and a light per beat. The section playing now and the one queued next are shown alongside.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'display.chord': {
    title: 'Chord',
    body: 'The chord the style is following. When Keyboard transpose is not zero, the chord as you fingered it is shown small underneath.',
    genos: 'Chord (Home display, Style area)',
    keys: [],
    launchkey: null,
  },
  'display.status': {
    title: 'Status line',
    body: 'The last message: a loaded style, an error, or a Launchkey note or CC nothing is mapped to, which tells you what a button really sends.',
    genos: null,
    keys: [],
    launchkey: null,
  },

  // ── Style ───────────────────────────────────────────────────────────────
  'style.name': {
    title: 'Style',
    body: 'The style that\'s loaded, and its folder. Click to browse the library.',
    genos: 'Style name',
    keys: ['enter'],
    launchkey: null,
  },
  'style.prev': {
    title: 'Previous style',
    body: 'Loads the previous style in the browser\'s order (folder, then name). While the band plays it keeps playing and follows your next chord in the new style.',
    genos: null,
    keys: ['←'],
    launchkey: '< Track button',
  },
  'style.next': {
    title: 'Next style',
    body: 'Loads the next style in the browser\'s order (folder, then name). While the band plays it keeps playing and follows your next chord in the new style.',
    genos: null,
    keys: ['→'],
    launchkey: 'Track > button',
  },

  // ── Style browser ───────────────────────────────────────────────────────
  'browser.open': {
    title: 'Browse styles',
    body: 'Opens the style browser: every style under the library folder, by folder. Your keyboard and the Launchkey keep playing while it\'s open.',
    genos: 'Style selection display',
    keys: ['enter'],
    launchkey: null,
  },
  'browser.filter': {
    title: 'Filter',
    body: 'Type to filter by style name, file name or folder (not case-sensitive). ↑/↓, PgUp/PgDn and Home/End move; Enter loads; Shift+Enter previews, or queues for the next bar while the band plays.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'browser.all': {
    title: 'All styles',
    body: 'Every style in the library, in the order < Track and Track > step through: folder, then name.',
    genos: null,
    keys: [],
    launchkey: '< Track and Track > step through this order',
  },
  'browser.folder': {
    title: 'Folder',
    body: 'Shows only the styles in this folder and its subfolders. The folder a style is in is its category.',
    genos: 'Style category',
    keys: [],
    launchkey: null,
  },
  'browser.favourites': {
    title: 'Favourites',
    body: 'The styles you starred, in library order. Favourites are remembered on this computer.',
    genos: 'Favorite',
    keys: [],
    launchkey: null,
  },
  'browser.recents': {
    title: 'Recent',
    body: 'The styles you loaded lately, newest first, however you loaded them. Remembered on this computer.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'browser.row': {
    title: 'Load style',
    body: 'Click or Enter loads this style and closes the browser. While the band plays it keeps playing and follows your next chord in the new style. ▶ marks the loaded style; ‹ and › mark the ones < Track and Track > would load.',
    genos: null,
    keys: [],
    launchkey: '< Track / Track > load the neighbouring rows',
  },
  'browser.row_error': {
    title: 'Unreadable style',
    body: 'This file couldn\'t be read as a style, so it can\'t be loaded and < Track / Track > skip it. The reason is shown on the row.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'browser.favourite': {
    title: 'Favourite',
    body: 'Stars or unstars this style, adding it to Favourites. Ctrl+D does the same for the highlighted row.',
    genos: 'Favorite',
    keys: [],
    launchkey: null,
  },
  'browser.preview': {
    title: 'Preview',
    body: 'While the band is stopped, plays a few bars of this style over a short default progression without loading it. Shift+Enter previews the highlighted row.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'browser.preview_stop': {
    title: 'Stop preview',
    body: 'Stops the preview at once. Loading a style, starting the band or closing the browser stops it too.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'browser.queue': {
    title: 'Load at next bar',
    body: 'While the band plays, loads this style on the next bar line instead of right away, so the change lands on the beat. Shift+Enter queues the highlighted row.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'browser.auto_preview': {
    title: 'Preview on select',
    body: 'When on and the band is stopped, the highlighted or hovered row previews after a short pause. Remembered on this computer.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'browser.close': {
    title: 'Close browser',
    body: 'Closes the browser without changing the style, and stops any preview.',
    genos: null,
    keys: ['esc'],
    launchkey: null,
  },

  // ── Chord detection ─────────────────────────────────────────────────────
  'fingering.select': {
    title: 'Fingering type',
    body: 'How your left hand\'s chords are read. The pads on page 2 pick one directly.',
    genos: 'Fingering Type',
    keys: ['f'],
    launchkey: `${P2}, top row, pads 1–7`,
  },
  'fingering.next': {
    title: 'Next fingering type',
    body: 'Steps to the next fingering type.',
    genos: 'Fingering Type',
    keys: ['f'],
    launchkey: null,
  },
  'fingering.single_finger': {
    title: 'Single Finger',
    body: 'One key plays a major chord. Add a black key to its left for minor, a white key for 7th, both for m7.',
    genos: 'Single Finger',
    keys: [],
    launchkey: pad(P2, 'top', 1),
  },
  'fingering.fingered': {
    title: 'Fingered',
    body: 'Play the whole chord. The bass is always the chord\'s root.',
    genos: 'Fingered',
    keys: [],
    launchkey: pad(P2, 'top', 2),
  },
  'fingering.fingered_on_bass': {
    title: 'Fingered On Bass',
    body: 'Like Fingered, but the lowest note you play becomes the bass, so you can play slash chords.',
    genos: 'Fingered On Bass',
    keys: [],
    launchkey: pad(P2, 'top', 3),
  },
  'fingering.multi_finger': {
    title: 'Multi Finger',
    body: 'Reads Single Finger and Fingered shapes both, without switching.',
    genos: 'Multi Finger',
    keys: [],
    launchkey: pad(P2, 'top', 4),
  },
  'fingering.ai_fingered': {
    title: 'AI Fingered',
    body: 'Like Fingered, but fewer than three keys can still give a chord, guessed from the chord before.',
    genos: 'AI Fingered',
    keys: [],
    launchkey: pad(P2, 'top', 5),
  },
  'fingering.full_keyboard': {
    title: 'Full Keyboard',
    body: 'Chords are read across the whole keyboard, even split between your hands.',
    genos: 'Full Keyboard',
    keys: [],
    launchkey: pad(P2, 'top', 6),
  },
  'fingering.ai_full_keyboard': {
    title: 'AI Full Keyboard',
    body: 'Full Keyboard with AI Fingered\'s guessing from fewer keys. 9th, 11th and 13th chords can\'t be played.',
    genos: 'AI Full Keyboard',
    keys: [],
    launchkey: pad(P2, 'top', 7),
  },
  'detection.upper': {
    title: 'Chord detection: Upper / Lower',
    body: 'Lower: your left hand plays the chords. Upper: your right hand does (as Fingered*), and your left hand is free for a bass line.',
    genos: 'Chord Detection Area',
    keys: ['d'],
    launchkey: pad(P2, 'top', 8),
  },
  'detection.manual_bass': {
    title: 'Manual Bass',
    body: 'In Upper, mutes the style\'s Bass and gives its voice to Left, so your left hand plays the bass. Left stays on while it\'s on. Dark in Lower, where it isn\'t available.',
    genos: 'Manual Bass',
    keys: ['D'],
    launchkey: pad(P2, 'bottom', 1),
  },
  'split.display': {
    title: 'Split point',
    body: 'The key that divides the chord section from the right hand (C3 = middle C). Right 1–3 play above it, Left and the chord section at and below it.',
    genos: 'Split Point (Style + Left)',
    keys: [],
    launchkey: null,
  },
  'split.down': {
    title: 'Split −',
    body: 'Moves the split point down one key.',
    genos: 'Split Point',
    keys: ['['],
    launchkey: pad(P2, 'bottom', 3),
  },
  'split.up': {
    title: 'Split +',
    body: 'Moves the split point up one key.',
    genos: 'Split Point',
    keys: [']'],
    launchkey: pad(P2, 'bottom', 4),
  },

  // ── Transpose ───────────────────────────────────────────────────────────
  'transpose.display': {
    title: 'Transpose',
    body: 'Keyboard transpose moves your keys and the chord the style follows. Master transpose moves everything that sounds, drums excepted.',
    genos: 'TRANSPOSE',
    keys: [],
    launchkey: null,
  },
  'transpose.keyboard_down': {
    title: 'Keyboard transpose −',
    body: 'Moves your keys and the chord the style follows down a semitone. The pad lights while it\'s below zero.',
    genos: 'TRANSPOSE − (Keyboard)',
    keys: [';'],
    launchkey: pad(P2, 'bottom', 5),
  },
  'transpose.keyboard_up': {
    title: 'Keyboard transpose +',
    body: 'Moves your keys and the chord the style follows up a semitone. The pad lights while it\'s above zero.',
    genos: 'TRANSPOSE + (Keyboard)',
    keys: ["'"],
    launchkey: pad(P2, 'bottom', 6),
  },
  'transpose.master_down': {
    title: 'Master transpose −',
    body: 'Moves everything that sounds down a semitone, the band included (not the drums).',
    genos: 'TRANSPOSE − (Master)',
    keys: [':'],
    launchkey: null,
  },
  'transpose.master_up': {
    title: 'Master transpose +',
    body: 'Moves everything that sounds up a semitone, the band included (not the drums).',
    genos: 'TRANSPOSE + (Master)',
    keys: ['"'],
    launchkey: null,
  },
  'transpose.reset': {
    title: 'Transpose reset',
    body: 'Puts Keyboard and Master transpose back to 0. The pad lights while either isn\'t 0.',
    genos: 'TRANSPOSE − and + together',
    keys: ['/'],
    launchkey: pad(P2, 'bottom', 7),
  },

  // ── One Touch Settings ──────────────────────────────────────────────────
  'ots.1': {
    title: 'OTS 1',
    body: 'A sound setup for your own hands that the style\'s author picked to suit it: the voice, on/off, volume and octave of Right 1–3 and Left. Pressing it swaps your keyboard sounds, and the band doesn\'t change. Dark if the style has none.',
    genos: 'ONE TOUCH SETTING 1',
    keys: ['shift+1'],
    launchkey: pad(P3, 'top', 1),
  },
  'ots.2': {
    title: 'OTS 2',
    body: 'The style\'s second suggested setup for your hands: the voice, on/off, volume and octave of Right 1–3 and Left. Pressing it swaps your keyboard sounds, and the band doesn\'t change.',
    genos: 'ONE TOUCH SETTING 2',
    keys: ['shift+2'],
    launchkey: pad(P3, 'top', 2),
  },
  'ots.3': {
    title: 'OTS 3',
    body: 'The style\'s third suggested setup for your hands: the voice, on/off, volume and octave of Right 1–3 and Left. Pressing it swaps your keyboard sounds, and the band doesn\'t change.',
    genos: 'ONE TOUCH SETTING 3',
    keys: ['shift+3'],
    launchkey: pad(P3, 'top', 3),
  },
  'ots.4': {
    title: 'OTS 4',
    body: 'The style\'s fourth suggested setup for your hands: the voice, on/off, volume and octave of Right 1–3 and Left. Pressing it swaps your keyboard sounds, and the band doesn\'t change.',
    genos: 'ONE TOUCH SETTING 4',
    keys: ['shift+4'],
    launchkey: pad(P3, 'top', 4),
  },
  'ots.link': {
    title: 'OTS Link',
    body: 'When on, your hands\' sounds follow the band: pressing Main A, B, C or D also recalls OTS 1, 2, 3 or 4. Changing style recalls the setting for the Main that\'s playing.',
    genos: 'OTS LINK',
    keys: ['F10'],
    launchkey: `${pad(P3, 'top', 5)}; Shift + Pad Bank ▼`,
  },

  // ── Keyboard parts ──────────────────────────────────────────────────────
  'part.right1.on': {
    title: 'Right 1 on/off',
    body: 'Turns Right 1 on or off. Right parts that are on sound together, which is how you layer voices.',
    genos: 'PART ON/OFF RIGHT 1',
    keys: ['5'],
    launchkey: `${pad(P3, 'bottom', 1)}; Panel fader page: button under fader 1`,
  },
  'part.right2.on': {
    title: 'Right 2 on/off',
    body: 'Turns Right 2 on or off. Turn on Right 1 and Right 2 together to layer, for example piano and strings.',
    genos: 'PART ON/OFF RIGHT 2',
    keys: ['6'],
    launchkey: `${pad(P3, 'bottom', 2)}; Panel fader page: button under fader 2`,
  },
  'part.right3.on': {
    title: 'Right 3 on/off',
    body: 'Turns Right 3 on or off, a third layer for the right hand.',
    genos: 'PART ON/OFF RIGHT 3',
    keys: ['7'],
    launchkey: `${pad(P3, 'bottom', 3)}; Panel fader page: button under fader 3`,
  },
  'part.left.on': {
    title: 'Left on/off',
    body: 'Turns the Left voice on or off: your left hand plays it below the split. It can\'t be turned off while Manual Bass is on.',
    genos: 'PART ON/OFF LEFT',
    keys: ['8', 'l'],
    launchkey: `${pad(P3, 'bottom', 4)}; Panel fader page: button under fader 4; Shift + Pad Bank ▲`,
  },
  'part.right1.select': {
    title: 'Edit Right 1',
    body: 'Picks Right 1 as the part whose voice Voice −/+ changes.',
    genos: 'Part select (Right 1)',
    keys: ['F1'],
    launchkey: `${pad(P3, 'bottom', 5)}; Panel fader page: Shift + button under fader 1`,
  },
  'part.right2.select': {
    title: 'Edit Right 2',
    body: 'Picks Right 2 as the part whose voice Voice −/+ changes.',
    genos: 'Part select (Right 2)',
    keys: ['F2'],
    launchkey: `${pad(P3, 'bottom', 6)}; Panel fader page: Shift + button under fader 2`,
  },
  'part.right3.select': {
    title: 'Edit Right 3',
    body: 'Picks Right 3 as the part whose voice Voice −/+ changes.',
    genos: 'Part select (Right 3)',
    keys: ['F3'],
    launchkey: `${pad(P3, 'bottom', 7)}; Panel fader page: Shift + button under fader 3`,
  },
  'part.left.select': {
    title: 'Edit Left',
    body: 'Picks Left as the part whose voice Voice −/+ changes.',
    genos: 'Part select (Left)',
    keys: ['F4'],
    launchkey: `${pad(P3, 'bottom', 8)}; Panel fader page: Shift + button under fader 4`,
  },
  'part.voice_down': {
    title: 'Voice −',
    body: 'Steps the selected part (the lit Edit pad) to the previous voice.',
    genos: 'Voice select',
    keys: ['9'],
    launchkey: pad(P3, 'top', 7),
  },
  'part.voice_up': {
    title: 'Voice +',
    body: 'Steps the selected part (the lit Edit pad) to the next voice.',
    genos: 'Voice select',
    keys: ['0'],
    launchkey: pad(P3, 'top', 8),
  },
  'part.octave_down': {
    title: 'Octave −',
    body: 'Shifts this part down an octave (down to −2). OTS recalls set it too.',
    genos: 'Voice Setting → Tune → Octave',
    keys: [],
    launchkey: null,
  },
  'part.octave_up': {
    title: 'Octave +',
    body: 'Shifts this part up an octave (up to +2). OTS recalls set it too.',
    genos: 'Voice Setting → Tune → Octave',
    keys: [],
    launchkey: null,
  },

  // ── Keyboard parts drawer ──────────────────────────────────────────────
  'part.voice': {
    title: 'Voice',
    body: 'Picks this part\'s voice. Under Manual Bass, Left plays the style\'s Bass voice instead, and this is the voice it goes back to.',
    genos: 'Voice select (VOICE buttons)',
    keys: [],
    launchkey: 'Pad page 3 (OTS/Parts): the Edit pads (bottom row, pads 5–8) pick the part, Voice −/+ (top row, pads 7–8) step its voice',
  },
  'part.layer': {
    title: 'Layer',
    body: 'The Right parts that are on all sound together on every key above the split: that\'s a layer. Turn on Right 1 and Right 2 to stack, for example, piano and strings.',
    genos: 'PART ON/OFF (Right 1–3 layered)',
    keys: ['5', '6', '7'],
    launchkey: 'Panel fader page: buttons under faders 1–3',
  },
  'part.left_zone': {
    title: 'Left hand',
    body: 'Left plays the keys at and below the split point, with its own voice. Under Manual Bass it plays the style\'s Bass voice there instead, and the band\'s own bass goes quiet.',
    genos: 'Split Point (Left)',
    keys: [],
    launchkey: null,
  },
  'part.written_for': {
    title: 'As written for',
    body: 'The voice the style\'s author wrote this band part for, and its MIDI channel on the yahaha port. Load a matching instrument on that channel in Ableton to hear the style as intended; ≈ marks the nearest General MIDI voice to a Yamaha one.',
    genos: 'Style parts (Mixer › Style)',
    keys: [],
    launchkey: null,
  },
  'ots.link_timing': {
    title: 'OTS Link timing',
    body: 'When OTS Link swaps the setting: as soon as you press a Main button, not when the band reaches the new Main at the bar line. The Genos calls this Real Time.',
    genos: 'OTS Link Timing: Real Time',
    keys: [],
    launchkey: null,
  },

  // ── Mixer ───────────────────────────────────────────────────────────────
  'mixer.page': {
    title: 'Fader page: Panel / Style',
    body: 'Switches what the Launchkey faders control: Panel is your four keyboard parts, Style is the band\'s eight parts. The button lights blue on Panel, green on Style.',
    genos: 'Mixer tabs (Panel / Style)',
    keys: ['F9'],
    launchkey: 'Button under the master fader',
  },
  'mixer.panel.right1': {
    title: 'Right 1 volume',
    body: 'Right 1\'s volume. The fader is channel 1\'s CC 7 itself, with no hidden gain behind it.',
    genos: 'Mixer › Panel › Right 1 Volume',
    keys: [],
    launchkey: 'Panel fader page: fader 1',
  },
  'mixer.panel.right2': {
    title: 'Right 2 volume',
    body: 'Right 2\'s volume. The fader is channel 3\'s CC 7 itself, with no hidden gain behind it.',
    genos: 'Mixer › Panel › Right 2 Volume',
    keys: [],
    launchkey: 'Panel fader page: fader 2',
  },
  'mixer.panel.right3': {
    title: 'Right 3 volume',
    body: 'Right 3\'s volume. The fader is channel 4\'s CC 7 itself, with no hidden gain behind it.',
    genos: 'Mixer › Panel › Right 3 Volume',
    keys: [],
    launchkey: 'Panel fader page: fader 3',
  },
  'mixer.panel.left': {
    title: 'Left volume',
    body: 'Left\'s volume. The fader is channel 2\'s CC 7 itself, with no hidden gain behind it; under Manual Bass it is the bass\'s level too.',
    genos: 'Mixer › Panel › Left Volume',
    keys: [],
    launchkey: 'Panel fader page: fader 4',
  },
  'mixer.style.volume': {
    title: 'Style part volume',
    body: 'This band part\'s volume. The fader is its channel\'s CC 7 itself (channels 9–16), with no hidden gain behind it, except that a Fade In/Out scales the CC 7 it sends while the fade runs (the fader stays put). Loading a style sets the faders to the style\'s own levels, and a pattern that changes its volume moves the fader too, until you move it yourself.',
    genos: 'Mixer › Style › Volume',
    keys: [],
    launchkey: 'Style fader page: faders 1–8 (Rhythm 1 … Phrase 2)',
  },
  'mixer.style.mute': {
    title: 'Style part on/off',
    body: 'Mutes or unmutes this band part. The Launchkey button is lit while the part plays.',
    genos: 'Channel On/Off',
    keys: ['z', 'x', 'c', 'v', 'b', 'n', 'm', ','],
    launchkey: 'Style fader page: buttons under faders 1–8',
  },
  'mixer.master': {
    title: 'Master volume',
    body: 'The built-in synth\'s output level (100 = unity), the only gain after the channel faders. A safety soft clipper above −1 dBFS keeps loud passages from hard clipping; below that the output is untouched. It does not change the MIDI output.',
    genos: 'MASTER VOLUME',
    keys: [],
    launchkey: 'Master fader (both fader pages)',
  },
  'mixer.solo': {
    title: 'Solo',
    body: 'Plays only this part, even if it is switched off; press again to end the solo. The Style tab solos a band part, the Panel tab a keyboard part, and the On switches stay as they were.',
    genos: 'Mixer › touch and hold a channel (Solo)',
    keys: [],
    launchkey: null,
  },
  'mixer.track_mute': {
    title: 'Style Track Mute',
    body: 'A knob for the band: fully left leaves one part on, and turning it up brings the others in one by one until all eight play. It switches the Style parts on and off, so the On buttons follow it.',
    genos: 'Live Control › Style Track Mute A/B (StyMuteA, StyMuteB)',
    keys: [],
    launchkey: null,
  },
  'mixer.track_mute_order': {
    title: 'Track Mute order',
    body: 'A starts from Rhythm 2, then Rhythm 1, Bass, Chord 1, Chord 2, Pad, Phrase 1 and Phrase 2. B starts from Chord 1, then Chord 2, Pad, Bass, Phrase 1, Phrase 2 and the rhythm parts last.',
    genos: 'Style Track Mute A / B',
    keys: [],
    launchkey: null,
  },
  'metronome.on': {
    title: 'Metronome',
    body: 'A click on every beat, with the band while it plays and on its own at the tempo while stopped. It sounds on the built-in synth only and never goes out on the MIDI port.',
    genos: 'Menu › Metronome › On/Off',
    keys: ['.'],
    launchkey: null,
  },
  'metronome.volume': {
    title: 'Metronome volume',
    body: 'The click\'s own level (0–127). The synth\'s master volume applies on top of it.',
    genos: 'Menu › Metronome › Volume',
    keys: [],
    launchkey: null,
  },
  'metronome.bell': {
    title: 'Bell on beat 1',
    body: 'A higher bell instead of the click on the first beat of each bar.',
    genos: 'Menu › Metronome › Bell Sound',
    keys: [],
    launchkey: null,
  },

  // ── Chord Looper ────────────────────────────────────────────────────────
  'looper.rec': {
    title: 'Chord Looper REC/STOP',
    body: 'Records the chords you play, from the next bar line; stopped, it arms Sync Start and your first chord starts the band and the recording together. Press again to stop recording while the band plays on.',
    genos: 'CHORD LOOPER [REC/STOP]',
    keys: ['r'],
    launchkey: null,
  },
  'looper.on_off': {
    title: 'Chord Looper ON/OFF',
    body: 'Loops the recorded chords from the next bar line, feeding them to the band as if you played them, so both hands are free. While it loops your chords are ignored; press again to stop it at once.',
    genos: 'CHORD LOOPER [ON/OFF]',
    keys: ['^'],
    launchkey: null,
  },
  'looper.memory': {
    title: 'Chord Looper memory',
    body: 'One of eight memories. Selecting one that holds a sequence makes it the loop; while looping it takes over at the next bar line.',
    genos: 'Chord Looper › Memory 1–8',
    keys: [],
    launchkey: null,
  },
  'looper.store': {
    title: 'Memory',
    body: 'Stores the current sequence: press it, then a memory number. The memory is named CLD_001 and on.',
    genos: 'Chord Looper › [Memory]',
    keys: [],
    launchkey: null,
  },
  'looper.clear': {
    title: 'Clear',
    body: 'Empties a memory: press it, then a memory number.',
    genos: 'Chord Looper › [Clear]',
    keys: [],
    launchkey: null,
  },
  'looper.new_bank': {
    title: 'New bank',
    body: 'Empties all eight memories. The current sequence stays.',
    genos: 'Chord Looper › New Bank',
    keys: [],
    launchkey: null,
  },
  'looper.sequence': {
    title: 'The sequence',
    body: 'The chords the loop plays, bar by bar; the bar playing is lit. Chord times snap to 16th notes and the loop is whole bars.',
    genos: 'Chord Looper (current data)',
    keys: [],
    launchkey: null,
  },
  'mixer.channel': {
    title: 'MIDI out channel',
    body: 'The channel this part plays on at yahaha\'s MIDI output: Right 1 = 1, Left = 2, Right 2 = 3, Right 3 = 4, the band 9–16. Map a DAW track (Ableton: MIDI From yahaha, this channel) to record or re-voice it.',
    genos: 'Part / Style channel',
    keys: [],
    launchkey: null,
  },
  'mixer.voice': {
    title: 'Voice',
    body: 'Keyboard parts: the GM voice the part plays. Style parts: the Yamaha voice (bank MSB/LSB/program) the style was written for, and after ≈ the nearest voice the built-in synth plays for it.',
    genos: 'Mixer › Voice',
    keys: [],
    launchkey: null,
  },
  'mixer.info': {
    title: 'A fader is the channel\'s CC 7',
    body: 'Each fader shows and sends exactly its channel\'s CC 7 (0–127), with no hidden gain anywhere, so the MIDI output and the synth hear the same level. Loading a style sets the Style faders to the style\'s own levels. While a Fade In/Out runs, the Style parts\' CC 7 goes out scaled by the fade, and the faders stay where they are.',
    genos: 'Mixer › Volume',
    keys: [],
    launchkey: 'The faders, on both fader pages',
  },
  'mixer.pickup': {
    title: 'Waiting for the fader',
    body: 'This level moved without the Launchkey fader (a style load, an OTS recall, a pattern, a page switch). The hardware fader does nothing until you move it to within 2 of the level, or across it.',
    genos: null,
    keys: [],
    launchkey: 'Soft takeover on every fader',
  },

  // ── Launchkey ───────────────────────────────────────────────────────────
  'padpage.sections': {
    title: 'Pad page 1: Sections',
    body: 'Intros, Mains, Break, Endings, Sync Start/Stop, Auto Fill, Tap and Start/Stop, each in its own colour.',
    genos: null,
    keys: ['tab', 'shift+tab'],
    app_keys: ['PgDn', 'PgUp'],
    launchkey: 'Pad Bank ▲ / ▼ (left of the pads)',
  },
  'padpage.chord_setup': {
    title: 'Pad page 2: Chord/Setup',
    body: 'Fingering types, Upper/Lower, Manual Bass, Stop ACMP, split and transpose. All cyan.',
    genos: null,
    keys: ['tab', 'shift+tab'],
    app_keys: ['PgDn', 'PgUp'],
    launchkey: 'Pad Bank ▲ / ▼ (left of the pads)',
  },
  'padpage.ots_parts': {
    title: 'Pad page 3: OTS/Parts',
    body: 'OTS 1–4 and OTS Link, voice −/+, keyboard parts on/off and which part to edit. All magenta.',
    genos: null,
    keys: ['tab', 'shift+tab'],
    app_keys: ['PgDn', 'PgUp'],
    launchkey: 'Pad Bank ▲ / ▼ (left of the pads)',
  },
  'padpage.prev': {
    title: 'Pad Bank ▲',
    body: 'Goes to the previous pad page, stopping at page 1, so a few presses always take you home. Lit in the page\'s colour when there\'s a page to go to. With Shift: Left on/off.',
    genos: null,
    keys: ['shift+tab'],
    app_keys: ['PgUp'],
    launchkey: 'Pad Bank ▲ (left of the pads)',
  },
  'padpage.next': {
    title: 'Pad Bank ▼',
    body: 'Goes to the next pad page, stopping at page 4. Lit in the page\'s colour when there\'s a page to go to. With Shift: OTS Link on/off.',
    genos: null,
    keys: ['tab'],
    app_keys: ['PgDn'],
    launchkey: 'Pad Bank ▼ (left of the pads)',
  },
  'launchkey.shift': {
    title: 'Shift',
    body: 'Hold for the second functions: Pad Bank ▲ = Left on/off, Pad Bank ▼ = OTS Link, the buttons under faders 1–4 on the Panel page = edit that part. On screen, click it to latch the Shift layer, or hold Shift on your computer keyboard.',
    genos: null,
    keys: [],
    launchkey: 'Shift button',
  },
  'launchkey.status': {
    title: 'Launchkey',
    body: 'Whether the Launchkey is connected in DAW mode, so its pads and buttons are arranger controls.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'launchkey.fader_unused': {
    title: 'Unused fader',
    body: 'On the Panel fader page, faders 5–8 and their buttons do nothing. Switch to the Style page (the button under the master fader) to mix the band.',
    genos: null,
    keys: [],
    launchkey: 'Panel fader page: faders 5–8 and the buttons under them',
  },
  'launchkey.unused': {
    title: 'Unused pad',
    body: 'This pad does nothing on this page and stays dark.',
    genos: null,
    keys: [],
    launchkey: null,
  },

  // ── Settings and audio ──────────────────────────────────────────────────
  'settings.open': {
    title: 'Settings',
    body: 'Chord detection, split, transpose, style behaviour, audio, MIDI and the style library. Changes apply at once.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'settings.close': {
    title: 'Close settings',
    body: 'Closes the settings panel.',
    genos: null,
    keys: ['esc'],
    launchkey: null,
  },
  'audio.output': {
    title: 'Audio output',
    body: 'The output pair the built-in synth plays on. `--audio-out N` sets it at launch.',
    genos: null,
    keys: ['a'],
    launchkey: null,
  },
  'audio.soundfont': {
    title: 'SoundFont',
    body: 'The General MIDI SoundFont (.sf2) the built-in synth plays, from the soundfonts folder. `--sf2 file` sets it at launch.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'audio.synth_mute': {
    title: 'Mute synth',
    body: 'Silences the built-in synth, for when you play Ableton\'s sounds from the yahaha MIDI port instead.',
    genos: null,
    keys: ['k'],
    launchkey: null,
  },
  'midi.input': {
    title: 'MIDI input',
    body: 'Whether this MIDI source plays yahaha. The Launchkey\'s DAW port carries its pads and buttons.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'settings.tab.chord': {
    title: 'Settings: Chord',
    body: 'Fingering type, chord detection area (Lower or Upper) and Manual Bass.',
    genos: 'Menu › Split & Fingering',
    keys: [],
    launchkey: `${P2}, top row (fingering, Upper) and bottom row, pad 1 (Manual Bass)`,
  },
  'settings.tab.split': {
    title: 'Settings: Split point',
    body: 'Where the keyboard divides between the chord section and the right hand.',
    genos: 'Menu › Split & Fingering › Split Point',
    keys: [],
    launchkey: `${P2}, bottom row, pads 3–4`,
  },
  'settings.tab.transpose': {
    title: 'Settings: Transpose',
    body: 'Keyboard and Master transpose, in semitones.',
    genos: 'Menu › Transpose',
    keys: [],
    launchkey: `${P2}, bottom row, pads 5–7`,
  },
  'settings.tab.style': {
    title: 'Settings: Style',
    body: 'How the band starts, stops and fills: Sync Start/Stop, Auto Fill and Stop Accompaniment.',
    genos: 'Menu › Style Setting',
    keys: [],
    launchkey: `${P1} (Sync Start, Sync Stop, Auto Fill); ${P2}, bottom row, pad 2 (Stop ACMP)`,
  },
  'settings.tab.audio': {
    title: 'Settings: Audio',
    body: 'The built-in synth: on or off, which output pair it plays on, its SoundFont and its master volume.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'settings.tab.midi': {
    title: 'Settings: MIDI',
    body: 'Which MIDI inputs play yahaha, the yahaha output port, and the Launchkey connection.',
    genos: 'Menu › MIDI',
    keys: [],
    launchkey: null,
  },
  'settings.tab.library': {
    title: 'Settings: Library',
    body: 'The folders yahaha looks for style files in, and a rescan.',
    genos: 'Style selection (USB / User folders)',
    keys: [],
    launchkey: null,
  },
  'settings.split_strip': {
    title: 'Split point',
    body: 'Drag the marker, or click a key, to set the split (C3 = middle C). Keys at and below it are Left and the chord section, keys above it play Right 1–3. With focus, ←/→ move it a key and PgUp/PgDn an octave.',
    genos: 'Split Point (Style + Left)',
    keys: ['[', ']'],
    launchkey: `${P2}, bottom row, pads 3–4`,
  },
  'settings.section_timing': {
    title: 'Section change timing: to Main',
    body: 'When a Main you press (or a style you load while playing) takes over. Next Bar: at once if you press within the bar\'s first beat, otherwise at the next bar line. Immediate: at the next beat, carrying on from that beat, except with Auto Fill on, where a Main change is always Next Bar.',
    genos: 'Section Change Timing – To Main [A]–[D]',
    keys: [],
    launchkey: null,
  },
  'settings.intro_ending_timing': {
    title: 'Section change timing: inside Intro/Ending',
    body: 'When you switch to another Intro or Ending while one plays. Next Bar: as for Mains. End of Section: the one playing finishes first, except Intro to Intro (Next Bar) and anything into Ending I (the next bar line).',
    genos: 'Section Change Timing – Inside Intro/Ending',
    keys: [],
    launchkey: null,
  },
  'settings.ots_link_timing': {
    title: 'OTS Link timing (coming soon)',
    body: 'With OTS Link on, whether the One Touch Setting changes the moment you press a Main (Immediate) or when the new Main actually starts (At Main Section Change). Coming in M5; for now it is always Immediate.',
    genos: 'OTS Link Timing',
    keys: [],
    launchkey: null,
  },
  'settings.chord_settle': {
    title: 'Chord settle',
    body: 'How long a new chord must hold still before the style follows it (0–30 ms; 0 follows every change at once). A chord whose keys land a few ms apart is then one chord change, not two, so no note is struck on the passing chord and cut a moment later. Only the accompaniment\'s chord parts wait (also Stop Accompaniment, and Multi Pads with Chord Match, even with the style stopped), and only when you change the chord on or just before their notes; drums keep time, and a chord struck a little ahead of the beat costs nothing.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'settings.synchro_stop_window': {
    title: 'Synchro Stop window',
    body: 'With Sync Stop on: hold a chord longer than this and Sync Stop turns itself off, so the style keeps playing when you let go. A quicker release still stops the style. Off (all the way left): Sync Stop never turns itself off.',
    genos: 'Synchro Stop Window',
    keys: [],
    launchkey: null,
  },
  'settings.fade_in': {
    title: 'Fade in time',
    body: 'How long a fade in takes to reach full volume, from 0 to 20 seconds.',
    genos: 'Fade In Time',
    keys: [],
    launchkey: null,
  },
  'settings.fade_out': {
    title: 'Fade out time',
    body: 'How long a fade out takes to reach silence before the band stops, from 0 to 20 seconds.',
    genos: 'Fade Out Time',
    keys: [],
    launchkey: null,
  },
  'settings.fade_hold': {
    title: 'Fade out hold time',
    body: 'How long the style stays silent after a fade out before its volume comes back, from 0 to 5 seconds.',
    genos: 'Fade Out Hold Time',
    keys: [],
    launchkey: null,
  },
  'settings.section_reset': {
    title: 'Tap: Section Reset',
    body: 'On: Tap while the band plays restarts the section from its top. Off: Tap always sets the tempo.',
    genos: 'Tap Tempo › Style Section Reset',
    keys: [],
    launchkey: null,
  },
  'settings.retrigger_rate': {
    title: 'Retrigger length',
    body: 'How much of the Main\'s start Retrigger loops: a whole note (1) down to a 32nd (1/32).',
    genos: 'Style Retrigger Rate (RtgRate)',
    keys: [],
    launchkey: 'Shift + > (Scene Launch) / Shift + Function buttons',
  },
  'audio.synth_on': {
    title: 'Built-in synth',
    body: 'Turns the built-in SoundFont synth\'s sound on or off. The yahaha MIDI port keeps playing either way, for Ableton or other sounds.',
    genos: null,
    keys: ['k'],
    launchkey: null,
  },
  'midi.merge_all': {
    title: 'Inputs: all or selected',
    body: 'All: every MIDI source plays yahaha, merged. Selected: only the sources you switch on below. `--all-inputs` and `--input name` set it at launch.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'midi.output': {
    title: 'yahaha MIDI output',
    body: 'The virtual MIDI port yahaha plays the band and your parts on. Pick it as a MIDI input in Ableton to use your own sounds.',
    genos: 'MIDI Transmit',
    keys: [],
    launchkey: null,
  },
  'midi.palette_leds': {
    title: 'Palette LEDs',
    body: 'Lights the Launchkey with its built-in palette colours and hardware flashing instead of exact RGB colours. Try it if the pads look wrong or lag. `--palette-leds` sets it at launch.',
    genos: null,
    keys: [],
    launchkey: 'Every pad and button light',
  },
  'settings.style_folders': {
    title: 'Style folders',
    body: 'The folders yahaha reads style files from (.sty, .prs, .sst and more), with subfolders as categories. Pass them on the command line or set YAHAHA_STYLES.',
    genos: 'Style selection (User / USB)',
    keys: [],
    launchkey: null,
  },
  'settings.rescan': {
    title: 'Rescan styles',
    body: 'Reads the style folders again, picking up files you added, changed or removed. The band keeps playing.',
    genos: null,
    keys: [],
    launchkey: null,
  },

  // ── Registration Memory ─────────────────────────────────────────────────
  'regist.1': {
    title: 'Registration 1',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [1]',
    keys: ['Q'],
    launchkey: pad(P4, 'top', 1),
  },
  'regist.2': {
    title: 'Registration 2',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [2]',
    keys: ['W'],
    launchkey: pad(P4, 'top', 2),
  },
  'regist.3': {
    title: 'Registration 3',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [3]',
    keys: ['E'],
    launchkey: pad(P4, 'top', 3),
  },
  'regist.4': {
    title: 'Registration 4',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [4]',
    keys: ['R'],
    launchkey: pad(P4, 'top', 4),
  },
  'regist.5': {
    title: 'Registration 5',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [5]',
    keys: ['T'],
    launchkey: pad(P4, 'top', 5),
  },
  'regist.6': {
    title: 'Registration 6',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [6]',
    keys: ['Y'],
    launchkey: pad(P4, 'top', 6),
  },
  'regist.7': {
    title: 'Registration 7',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [7]',
    keys: ['U'],
    launchkey: pad(P4, 'top', 7),
  },
  'regist.8': {
    title: 'Registration 8',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [8]',
    keys: ['I'],
    launchkey: pad(P4, 'top', 8),
  },
  'regist.9': {
    title: 'Registration 9',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [9]',
    keys: ['O'],
    launchkey: pad(P4, 'bottom', 1),
  },
  'regist.10': {
    title: 'Registration 10',
    body: 'Recalls the panel stored on this button: style, section, tempo, your parts, the mixer, split and more (the groups it memorized, less any you froze). Blue when it holds a setup, red when it is the one in use, dark when empty. With Memory armed, stores the panel here instead.',
    genos: 'REGISTRATION MEMORY [10]',
    keys: ['P'],
    launchkey: pad(P4, 'bottom', 2),
  },
  'regist.memory': {
    title: 'Memory',
    body: 'Arms Memorize: the next Registration button you press stores the whole panel (the ticked Memorize groups) on it, replacing what it held. The buttons flash while it waits. Press Memory again to cancel.',
    genos: 'MEMORY',
    keys: ['F5'],
    launchkey: pad(P4, 'bottom', 5),
  },
  'regist.freeze': {
    title: 'Freeze',
    body: 'While on, recalling a registration leaves the ticked Freeze groups as they are: freeze Style to change voices without changing the band, or Tempo to keep your tempo.',
    genos: 'FREEZE',
    keys: ['F6'],
    launchkey: pad(P4, 'bottom', 6),
  },
  'regist.seq_prev': {
    title: 'Regist −',
    body: 'Steps back through the bank\'s Registration Sequence and recalls that button. Works only while the sequence is on.',
    genos: 'Registration Sequence − (Regist − pedal)',
    keys: ['F7'],
    launchkey: pad(P4, 'bottom', 7),
  },
  'regist.seq_next': {
    title: 'Regist +',
    body: 'Steps forward through the bank\'s Registration Sequence and recalls that button, like a pedal on stage. At the end it stops, starts again, or moves to the next bank, as the sequence says.',
    genos: 'Registration Sequence + (Regist + pedal)',
    keys: ['F8'],
    launchkey: pad(P4, 'bottom', 8),
  },
  'regist.bank_prev': {
    title: 'Bank −',
    body: 'Loads the previous bank file in the Registration folder. Its buttons light up but nothing is recalled until you press one.',
    genos: 'REGIST BANK −',
    keys: ['F11'],
    launchkey: pad(P4, 'bottom', 3),
  },
  'regist.bank_next': {
    title: 'Bank +',
    body: 'Loads the next bank file in the Registration folder. Its buttons light up but nothing is recalled until you press one.',
    genos: 'REGIST BANK +',
    keys: ['F12'],
    launchkey: pad(P4, 'bottom', 4),
  },
  'regist.bank': {
    title: 'Bank',
    body: 'The bank of ten buttons in use. Pick another bank file from the Registration folder; a star means it has changes that aren\'t saved yet.',
    genos: 'Registration Bank Selection',
    keys: [],
    launchkey: null,
  },
  'regist.open': {
    title: 'Registration and Playlist',
    body: 'Opens the Registration panel: what each button holds, renaming and clearing, the Memory and Freeze groups, the Registration Sequence and the Playlist.',
    genos: 'Regist Bank Info / Edit, Regist Sequence, Regist Freeze, PLAYLIST',
    keys: [],
    launchkey: null,
  },
  'regist.tab': {
    title: 'Registration panel page',
    body: 'Switches between the bank\'s buttons, the Memory and Freeze groups, the Registration Sequence and the Playlist.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'regist.new_bank': {
    title: 'New bank',
    body: 'Starts a new, empty bank. Give it a name and save it to keep it; unsaved changes to the bank in use are dropped.',
    genos: 'Regist Bank: New',
    keys: [],
    launchkey: null,
  },
  'regist.save_bank': {
    title: 'Save bank',
    body: 'Saves the bank to its file in the Registration folder, or under the name you typed as a new file. If another bank already has that name, nothing is saved: pick another name, or use Overwrite. Once a bank has a file, memorizing, renaming and sequence edits save themselves.',
    genos: 'Regist Bank: Save',
    keys: [],
    launchkey: null,
  },
  'regist.overwrite_bank': {
    title: 'Overwrite bank',
    body: 'Another bank already has the name you typed. Overwrite replaces that bank\'s file with this bank; what it held is lost.',
    genos: 'Regist Bank: Save (overwrite)',
    keys: [],
    launchkey: null,
  },
  'regist.bank_name': {
    title: 'Bank name',
    body: 'The name to save the bank under. Saving with a new name makes a new file and leaves the old one as it was. A name another bank already has is refused, unless you choose Overwrite.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'regist.info': {
    title: 'Button contents',
    body: 'What this button holds: its style, tempo and the voices of Right 1–3 and Left. Click it to recall it.',
    genos: 'Regist Bank Info',
    keys: [],
    launchkey: null,
  },
  'regist.memorize_here': {
    title: 'Memorize here',
    body: 'Stores the panel as it is now on this button (the ticked Memorize groups), replacing what it held.',
    genos: 'MEMORY + [1]–[10]',
    keys: [],
    launchkey: null,
  },
  'regist.rename': {
    title: 'Rename',
    body: 'Renames this button. The name shows in the Registration bar and in playlists.',
    genos: 'Regist Bank Edit: Rename',
    keys: [],
    launchkey: null,
  },
  'regist.clear': {
    title: 'Clear',
    body: 'Empties this button. Its lamp goes dark.',
    genos: 'Regist Bank Edit: Delete',
    keys: [],
    launchkey: null,
  },
  'regist.memorize_group': {
    title: 'Memorize group',
    body: 'Ticked groups are what Memory stores on a button; a recall only changes what the button stored. Untick Tempo, say, for buttons that should keep whatever tempo you are playing.',
    genos: 'Registration Memory window (items to register)',
    keys: [],
    launchkey: null,
  },
  'regist.freeze_group': {
    title: 'Freeze group',
    body: 'Ticked groups stay as they are when you recall a registration, while Freeze is on. Style also covers the section, the Style mixer, the split, the fingering and the Left part, as on the Genos.',
    genos: 'Regist Freeze display',
    keys: [],
    launchkey: null,
  },
  'regist.sequence_on': {
    title: 'Registration Sequence',
    body: 'Turns the Registration Sequence on, so Regist + and Regist − step through the bank\'s sequence. As on the Genos this is a panel setting, not part of the bank: it stays as it is when you change banks, and yahaha remembers it between sessions.',
    genos: 'Registration Sequence On/Off',
    keys: [],
    launchkey: null,
  },
  'regist.sequence_steps': {
    title: 'Add step',
    body: 'Adds this button to the end of the sequence. A button can come more than once.',
    genos: 'Registration Sequence: Insert',
    keys: [],
    launchkey: null,
  },
  'regist.sequence_step': {
    title: 'Sequence step',
    body: 'A step of the sequence: the button it recalls. Click to take it out of the sequence; the ringed step is the one last recalled.',
    genos: 'Registration Sequence: Delete',
    keys: [],
    launchkey: null,
  },
  'regist.sequence_clear': {
    title: 'Clear sequence',
    body: 'Removes every step from the sequence.',
    genos: 'Registration Sequence: Clear',
    keys: [],
    launchkey: null,
  },
  'regist.sequence_end': {
    title: 'At the end',
    body: 'What Regist + does after the last step: Stop does nothing more, Top starts again at the first step, Next bank moves on to the next bank file and its first step.',
    genos: 'Registration Sequence end (Stop / Top / Next)',
    keys: [],
    launchkey: null,
  },
  'padpage.registration': {
    title: 'Pad page 4: Registration',
    body: 'Registration buttons 1–10 in the Genos lamp colours (red in use, blue stored, dark empty), Bank −/+, Memory, Freeze and Regist −/+. The other pads are orange.',
    genos: null,
    keys: ['tab', 'shift+tab'],
    app_keys: ['PgDn', 'PgUp'],
    launchkey: 'Pad Bank ▲ / ▼ (left of the pads)',
  },

  // ── Playlist ────────────────────────────────────────────────────────────
  'playlist.prev': {
    title: 'Previous song',
    body: 'Loads the playlist record before the one in use: its bank and button, or its style.',
    genos: 'Playlist (previous record)',
    keys: ['<'],
    launchkey: 'Shift + < Track button',
  },
  'playlist.next': {
    title: 'Next song',
    body: 'Loads the next playlist record: its bank and button, or its style. Step through a set list this way without looking at the screen.',
    genos: 'Playlist (next record)',
    keys: ['>'],
    launchkey: 'Shift + Track > button',
  },
  'playlist.record': {
    title: 'Playlist record',
    body: 'A song in the set list. Click it to load its bank (and recall its button) or its style; the lit one is the song in use. A struck-out name means its file is gone.',
    genos: 'Playlist Record (Load)',
    keys: [],
    launchkey: null,
  },
  'playlist.file': {
    title: 'Playlist',
    body: 'The set list in use. Pick another playlist file from the Playlists folder; a star means it has unsaved changes.',
    genos: 'Playlist File Selection',
    keys: [],
    launchkey: null,
  },
  'playlist.new': {
    title: 'New playlist',
    body: 'Starts a new, empty set list. Unsaved changes to the one in use are dropped.',
    genos: 'Playlist: New',
    keys: [],
    launchkey: null,
  },
  'playlist.save': {
    title: 'Save playlist',
    body: 'Saves the set list in the order shown (a sorted list is saved sorted, and goes back to Normal), to its file or under the name you typed. A name another playlist already has is refused: pick another, or use Overwrite.',
    genos: 'Playlist: Save',
    keys: [],
    launchkey: null,
  },
  'playlist.overwrite': {
    title: 'Overwrite playlist',
    body: 'Another playlist already has the name you typed. Overwrite replaces that playlist\'s file with this set list.',
    genos: 'Playlist: Save (overwrite)',
    keys: [],
    launchkey: null,
  },
  'playlist.name': {
    title: 'Playlist name',
    body: 'The name to save the set list under. A new name makes a new file; another playlist\'s name needs Overwrite.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'playlist.add_bank': {
    title: 'Add this bank',
    body: 'Adds the bank in use to the end of the set list, recalling the button that is lit. The bank must be saved first.',
    genos: 'Add Record: Select from Registration Bank',
    keys: [],
    launchkey: null,
  },
  'playlist.add_style': {
    title: 'Add this style',
    body: 'Adds the loaded style to the end of the set list, for a song that needs only the style.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'playlist.append': {
    title: 'Append playlist',
    body: 'Adds every record of another playlist file to the end of this one.',
    genos: 'Add Record: Append Playlist',
    keys: [],
    launchkey: null,
  },
  'playlist.edit': {
    title: 'Button to recall',
    body: 'Which button of the bank this record recalls after loading it, or none to only load the bank.',
    genos: 'Record Edit: Load Regist Memory',
    keys: [],
    launchkey: null,
  },
  'playlist.up': {
    title: 'Move up',
    body: 'Moves the record one place up the set list. Off while the list is sorted.',
    genos: 'Playlist: Up',
    keys: [],
    launchkey: null,
  },
  'playlist.down': {
    title: 'Move down',
    body: 'Moves the record one place down the set list. Off while the list is sorted.',
    genos: 'Playlist: Down',
    keys: [],
    launchkey: null,
  },
  'playlist.delete': {
    title: 'Delete record',
    body: 'Takes the record out of the set list; its bank or style file is not touched. Off while the list is sorted.',
    genos: 'Playlist: Delete',
    keys: [],
    launchkey: null,
  },
  'playlist.sort': {
    title: 'Sort',
    body: 'Shows the set list in its own order, A to Z or Z to A. Saving while sorted saves that order.',
    genos: 'Playlist: Sort (A to Z)',
    keys: [],
    launchkey: null,
  },

  // ── Pedals and wheels (Settings › Pedals) ───────────────────────────────
  'settings.tab.controllers': {
    title: 'Pedals and wheels',
    body: 'The sustain pedal and footswitches, what each pedal does, and which parts the pedal and the wheels reach.',
    genos: 'Assignable, Controller',
    keys: [],
    launchkey: null,
  },
  'pedal.function': {
    title: 'Pedal function',
    body: 'What this pedal does: Sustain (or Sostenuto, Soft), a style control such as Start/Stop, Fill Up or Break, an OTS, the Registration bank, tempo, transpose or a part on/off.',
    genos: 'Assignable › Foot Pedal',
    keys: [],
    launchkey: 'The pedal plugged into the sustain jack',
  },
  'pedal.cc': {
    title: 'Pedal CC',
    body: "The control change this pedal listens for on the keyboards: the Launchkey's sustain jack sends CC 64. Clear it and the pedal listens to nothing. Bank select (0, 32), the modulation wheel (1), data entry (6, 38), volume (7), (N)RPN (98-101) and the channel mode messages (120-127) can't be used.",
    genos: null,
    keys: [],
    launchkey: 'The sustain jack (CC 64)',
  },
  'pedal.learn': {
    title: 'Learn',
    body: "Press this, then the pedal: it takes that pedal's CC. Press again to stop waiting.",
    genos: null,
    keys: [],
    launchkey: 'The sustain jack (CC 64)',
  },
  'pedal.try': {
    title: 'Try',
    body: "Runs the pedal's function now, as a press would. Sustain, Sostenuto and Soft switch on or off, and stay that way until you press Try again. Modulation and Pitch Bend follow the pedal, so there is nothing to try here.",
    genos: null,
    keys: [],
    launchkey: null,
  },
  'pedal.reverse': {
    title: 'Reverse polarity',
    body: 'For a pedal that works the wrong way round (nothing when pressed, something when let go).',
    genos: 'Polarity',
    keys: [],
    launchkey: null,
  },
  'pedal.hold_a': {
    title: 'Hold A',
    body: 'On while the pedal is held, off when it is let go: how a sustain pedal works.',
    genos: 'Control Type: Hold A',
    keys: [],
    launchkey: null,
  },
  'pedal.hold_b': {
    title: 'Hold B',
    body: 'Off while the pedal is held, on when it is up: picking it with the pedal up turns the function on at once.',
    genos: 'Control Type: Hold B',
    keys: [],
    launchkey: null,
  },
  'pedal.toggle': {
    title: 'Toggle',
    body: 'Each press switches it on or off.',
    genos: 'Control Type: Toggle',
    keys: [],
    launchkey: null,
  },
  'pedal.range_upper': {
    title: 'Bend up',
    body: 'An expression pedal bends the pitch up: heel down is no bend, toe down the full Pitch Bend Range.',
    genos: 'Range: Upper',
    keys: [],
    launchkey: null,
  },
  'pedal.range_lower': {
    title: 'Bend down',
    body: 'An expression pedal bends the pitch down: heel down is no bend, toe down the full range down.',
    genos: 'Range: Lower',
    keys: [],
    launchkey: null,
  },
  'pedal.range_full': {
    title: 'Bend both ways',
    body: 'The pedal sweeps the whole bend: heel down is fully down, the middle no bend, toe down fully up.',
    genos: 'Range: Full',
    keys: [],
    launchkey: null,
  },
  'pedal.part_sustain': {
    title: 'Sustain on this part',
    body: 'Whether the sustain pedal (and Sostenuto and Soft) reach this part. A part only takes it while it is on.',
    genos: 'Sustain (part settings)',
    keys: [],
    launchkey: null,
  },
  'pedal.part_bend': {
    title: 'Pitch bend on this part',
    body: 'Whether the pitch-bend wheel (or a Pitch Bend pedal) bends this part.',
    genos: 'Joystick (X): Pitch Bend',
    keys: [],
    launchkey: 'The pitch wheel',
  },
  'pedal.part_modulation': {
    title: 'Modulation on this part',
    body: "Whether the modulation wheel adds vibrato to this part. By default Right 1–3 take it and Left doesn't.",
    genos: 'Joystick (Y): Modulation',
    keys: [],
    launchkey: 'The modulation wheel',
  },
  'pedal.bend_down': {
    title: 'Pitch Bend Range down',
    body: 'One semitone less bend for this part (0–12; 2 is the default).',
    genos: 'Pitch Bend Range',
    keys: [],
    launchkey: null,
  },
  'pedal.bend_up': {
    title: 'Pitch Bend Range up',
    body: 'One semitone more bend for this part (0–12).',
    genos: 'Pitch Bend Range',
    keys: [],
    launchkey: null,
  },


  // ── Drawers around the hardware view ────────────────────────────────────
  'drawer.parts': {
    title: 'Keyboard parts and OTS',
    body: 'Opens the detail of Right 1–3 and Left (voice, volume, octave, on/off) and the style\'s One Touch Settings.',
    genos: 'PART ON/OFF, Voice Setting, ONE TOUCH SETTING',
    keys: [],
    launchkey: 'Pad page 3 (OTS/Parts) has the same controls',
  },
  'drawer.mixer': {
    title: 'Mixer',
    body: 'Opens the full mixer: both fader pages side by side, with each band part\'s voice.',
    genos: 'Mixer (Panel / Style tabs)',
    keys: [],
    launchkey: 'The faders and the buttons under them',
  },
  'drawer.looper': {
    title: 'Chord Looper',
    body: 'Opens the Chord Looper: record a chord progression, loop it, and keep it in one of eight memories.',
    genos: 'Menu › Chord Looper',
    keys: [],
    launchkey: null,
  },
  'drawer.close': {
    title: 'Close',
    body: 'Closes this panel. The band keeps playing.',
    genos: null,
    keys: ['esc'],
    launchkey: null,
  },

  // ── Multi Pads ──────────────────────────────────────────────────────────
  'drawer.multipad': {
    title: 'Multi Pads',
    body: 'Opens the Multi Pads: four short phrases from a pad bank that you trigger over the band, and the bank list.',
    genos: 'MULTI PAD CONTROL',
    keys: [],
    launchkey: null,
  },
  'multipad.pad': {
    title: 'Multi Pad',
    body: 'Plays the pad\'s phrase from the top (keys Shift+Z, X, C, V): at once when the band is stopped, at the next bar line while it plays. With pads in Synchro Start standby, pressing one of them starts them all. Blue: has data; red: playing; flashing red: waiting for Synchro Start; amber: waiting for the bar line.',
    genos: 'MULTI PAD CONTROL [1]–[4]',
    keys: ['Z', 'X', 'C', 'V'],
    launchkey: null,
  },
  'multipad.stop_all': {
    title: 'Stop all pads',
    body: 'Stops every Multi Pad at once and cancels Synchro Start standby. The band keeps playing. Key: Shift+B.',
    genos: 'MULTI PAD CONTROL [STOP]',
    keys: ['B'],
    launchkey: null,
  },
  'multipad.stop': {
    title: 'Stop this pad',
    body: 'Stops only this pad, now. The other pads keep playing.',
    genos: '[STOP] + pad',
    keys: [],
    launchkey: null,
  },
  'multipad.arm': {
    title: 'Synchro Start',
    body: 'Puts the pad in standby (flashing red): it starts with your next chord in the chord section, when the band starts, or when you press any pad in standby; while the band plays, at the next bar line. Press again to cancel.',
    genos: '[SELECT] + pad (Synchro Start)',
    keys: [],
    launchkey: null,
  },
  'multipad.repeat': {
    title: 'Repeat',
    body: 'On: the pad loops until you stop it. Off: it plays once. The bank file sets it; a change here lasts until another bank loads.',
    genos: 'Repeat (Multi Pad Edit)',
    keys: [],
    launchkey: null,
  },
  'multipad.chord_match': {
    title: 'Chord Match',
    body: 'On: the pad follows the chord you play, like the band does. Off: it plays exactly as recorded, as drum pads usually do.',
    genos: 'Chord Match (Multi Pad Edit)',
    keys: [],
    launchkey: null,
  },
  'multipad.bank': {
    title: 'Multi Pad bank',
    body: 'Loads this bank\'s four pads. Pads playing stop. The list is every .pad file in your style folders.',
    genos: 'Multi Pad Bank Selection',
    keys: [],
    launchkey: null,
  },
  'multipad.clear': {
    title: 'No bank',
    body: 'Unloads the bank: the pads go dark.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'multipad.synchro_style_stop': {
    title: 'Synchro Stop: Style Stop',
    body: 'On: looping pads stop when the band stops. Off: they play on until you stop them.',
    genos: 'Multi Pad Synchro Stop (Style Stop)',
    keys: [],
    launchkey: null,
  },
  'multipad.synchro_ending': {
    title: 'Synchro Stop: Style Ending',
    body: 'On: looping pads stop when an Ending starts. Off: they play through the Ending.',
    genos: 'Multi Pad Synchro Stop (Style Ending)',
    keys: [],
    launchkey: null,
  },

  // ── Main screen: lead-sheet band and keyboard strip ─────────────────────
  'lead.section': {
    title: 'Section playing',
    body: 'The section the band is playing now, and before the start the Main (and any Intro) it will start with.',
    genos: 'Section (MAIN VARIATION, INTRO, ENDING)',
    keys: [],
    launchkey: 'Pad page 1 (Sections) shows it lit',
  },
  'lead.progress': {
    title: 'Section progress',
    body: 'One cell per bar of the section, filling beat by beat, so you can see how far into the pattern the band is. This band will also show the chord chart when one is loaded.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'lead.next': {
    title: 'Next section',
    body: 'The section queued to play next. A Main or Ending takes over at the next bar line, a fill at the next beat.',
    genos: null,
    keys: [],
    launchkey: 'Pad page 1 (Sections): the queued pad flashes',
  },
  'keystrip.keys': {
    title: 'Keyboard',
    body: 'The keys you are holding, coloured by the part that sounds them: Right 1–3 above the split, Left below it, grey where a key only feeds chord detection. The shaded band is where chord detection listens, and dots mark the tones of the recognised chord, the ringed one its bass. The engine doesn\'t report held keys or chord tones yet; until it does, the strip shows only the split and the detection area.',
    genos: 'Keyboard (Split Point, chord detection area)',
    keys: [],
    launchkey: "The Launchkey's keys",
  },
  'keystrip.split': {
    title: 'Split point',
    body: 'Where the left-hand section ends (C3 = middle C). Drag the marker, or focus it and use the arrow keys, to move it one key at a time.',
    genos: 'Split Point (Style + Left)',
    keys: ['[', ']'],
    launchkey: `${pad(P2, 'bottom', 3)} and 4`,
  },
  'keystrip.range': {
    title: 'Keyboard size',
    body: 'How many keys the strip shows: 49 or 61 like your Launchkey, or a full 88. It matches the connected Launchkey until you pick one; pick the lit one again to go back to matching.',
    genos: null,
    keys: [],
    launchkey: null,
  },

  // ── App ─────────────────────────────────────────────────────────────────
  'app.help': {
    title: 'Help mode',
    body: 'Grows the help footer to show the whole entry, and keeps the last control you hovered or tabbed to there while you try it. Controls keep working.',
    genos: null,
    keys: ['?'],
    launchkey: null,
  },
  'app.floating_tips': {
    title: 'Pop-up tips',
    body: 'Also shows each entry in a pop-up next to the control, as well as in the help footer. Off by default, because a pop-up covers the controls while you play.',
    genos: null,
    keys: [],
    launchkey: null,
  },
  'app.theme': {
    title: 'Light / dark',
    body: 'Switches between the dark stage theme and a light one.',
    genos: null,
    keys: [],
    launchkey: null,
  },
} satisfies Record<string, Tip>

export type TipKey = keyof typeof catalog
export const TIPS: Record<TipKey, Tip> = catalog

export function isTipKey(k: string): k is TipKey {
  return Object.prototype.hasOwnProperty.call(catalog, k)
}

const KEY_NAMES: Record<string, string> = {
  space: 'Space', enter: 'Enter', esc: 'Esc', tab: 'Tab', 'shift+tab': 'Shift+Tab', '\\': '\\',
}

/** A key as a keycap shows it: `shift+1` → `Shift+1`, `D` → `Shift+D`. */
export function keyLabel(k: string): string {
  if (KEY_NAMES[k]) return KEY_NAMES[k]
  if (k.startsWith('shift+')) return 'Shift+' + k.slice(6).toUpperCase()
  if (/^[A-Z]$/.test(k)) return 'Shift+' + k
  return k.length === 1 ? k.toUpperCase() : k
}
